add getaltdeiver method for c#
alttester/AltTester-Unity-SDK pull request #1036
Opened 2022-12-22 15:04 UTC by SandyEma9

2023-01-03 10:04 UTC, SandyEma9 commented
@robert-altom @RobertPoienar @gomboskriszta15 @ReichEdvin

2023-01-04 14:02 UTC, RobertPoienar requested changes
You change only to some test file but there are multiple tests file which still have the old instantiations.

Also it would be nice if we would have a base class that has a setup method a  tear down method and all the tests inherit that base class

2023-01-11 12:24 UTC, SandyEma9 commented
@gomboskriszta15 @RobertPoienar @robert-altom @ReichEdvin

2023-01-12 11:34 UTC, gomboskriszta15 approved these changes

2023-01-12 12:15 UTC, robert-altom approved these changes

2023-01-12 13:59 UTC, RobertPoienar approved these changes

2023-01-12 14:00 UTC, merged