add GetApplicationScreenSize method
alttester/AltTester-Unity-SDK pull request #1037
Opened 2023-01-03 11:29 UTC by SandyEma9

2023-01-09 11:02 UTC, SandyEma9 commented
@RobertPoienar @robert-altom @gomboskriszta15 @ReichEdvin

2023-01-10 08:59 UTC, RobertPoienar requested changes
Please add documentation

2023-01-10 09:05 UTC, gomboskriszta15 approved these changes

2023-01-11 15:12 UTC, RobertPoienar approved these changes

2023-01-11 15:13 UTC, merged