Rename gameName to appName
alttester/AltTester-Unity-SDK pull request #1122
Opened 2023-02-16 10:39 UTC by robert-altom

2023-02-27 08:10 UTC, robert-altom commented
Ping @RobertPoienar @gomboskriszta15 @ReichEdvin

2023-02-28 07:53 UTC, RobertPoienar requested changes
Just a little comment, the rest looks ok

2023-02-28 07:53 UTC, RobertPoienar commented on Assets/AltTester/AltDriver/AltDriver.cs
> +        public AltDriver(string host = "127.0.0.1", int port = 13000, bool enableLogging = false, int connectTimeout = 60, string appName = "__default__")
Can you please document the appName parameter

2023-02-28 08:08 UTC, iulianatodoran commented on Assets/Editor/CreateAltPrefab.cs
> +            LabelText.text = "To change the host, port or game name input a new value and press the Restart button.";
should be `app name` here

2023-02-28 08:14 UTC, iulianatodoran commented
In the `AltDesktopPage.cs` there are 2 references to the `game`, maybe they should be also changed with `app`
![image](https://user-images.githubusercontent.com/62327834/221793090-74dbdb37-072f-4134-a4b1-37746c6b8e1f.png)

2023-02-28 08:44 UTC, iulianatodoran commented
All the screenshots with the `game` and `AltProxy` name need to be updated also

2023-02-28 09:02 UTC, iulianatodoran commented
Found that in all these files there are references to the game. should they also be changed?
![image](https://user-images.githubusercontent.com/62327834/221803910-896c4cf5-d66e-4fe1-ab11-a50cc13749db.png)

2023-02-28 09:10 UTC, robert-altom commented
> Found that in all these files there are references to the game. should they also be changed? ![image](https://user-images.githubusercontent.com/62327834/221803910-896c4cf5-d66e-4fe1-ab11-a50cc13749db.png)

I fixed the ones from docstings and `README.md`.

2023-02-28 09:12 UTC, robert-altom commented
> All the screenshots in the documentation with the `game` and `AltProxy` name need to be updated also

We also need to uncomment and update all references to `AltProxy`.

2023-02-28 09:14 UTC, robert-altom commented
> In the `AltDesktopPage.cs` there are 2 references to the `game`, maybe they should be also changed with `app` ![image](https://user-images.githubusercontent.com/62327834/221793090-74dbdb37-072f-4134-a4b1-37746c6b8e1f.png)

Fixed.

2023-02-28 09:33 UTC, robert-altom commented on Assets/Editor/CreateAltPrefab.cs
> +            LabelText.text = "To change the host, port or game name input a new value and press the Restart button.";
Fixed.

2023-02-28 13:35 UTC, RobertPoienar approved these changes

2023-02-28 13:39 UTC, iulianatodoran approved these changes

2023-02-28 13:40 UTC, merged