Save last successful connection info
alttester/AltTester-Unity-SDK pull request #1347
Opened 2023-07-28 12:18 UTC by gomboskriszta15

2023-07-28 17:19 UTC, RobertPoienar requested changes

2023-07-28 17:19 UTC, RobertPoienar commented on Assets/AltTester/Runtime/UI/AltDialog.cs
> +        private readonly string APP_NAME = "appName";
Please make this value less generic in order to not overwrite if also the client users use this

2023-07-31 08:13 UTC, RobertPoienar approved these changes

2023-07-31 08:28 UTC, rucindrea approved these changes

2023-07-31 08:28 UTC, merged