[Concurrency] Connection with AltServer established immediately after changing Host/Port on Green Popup without restarting the connection data
alttester/AltTester-Unity-SDK pull request #1478
Opened 2024-01-16 13:38 UTC by gomboskriszta15

2024-01-16 14:30 UTC, gomboskriszta15 commented
@alttester/developers

2024-01-17 11:38 UTC, RobertPoienar requested changes

2024-01-17 11:38 UTC, RobertPoienar commented on Assets/AltTester/Runtime/UI/AltDialog.cs
> +                currentPort = "";
I don't think you need to changes these variable

2024-01-17 11:54 UTC, iulianatodoran approved these changes

2024-01-17 12:28 UTC, RobertPoienar approved these changes

2024-01-17 12:28 UTC, merged