1501 add support for concurrency robot framework
alttester/AltTester-Unity-SDK pull request #1503
Opened 2024-02-08 16:16 UTC by rucindrea

This depends on https://github.com/alttester/AltTester-Unity-SDK/pull/1499 and needs to be merged only after that.

2024-02-08 16:17 UTC, rucindrea commented
@alttester/developers

2024-02-12 08:19 UTC, RobertPoienar requested changes

2024-02-12 08:19 UTC, RobertPoienar commented on Bindings~/robot/tests/test_driver.robot
> +*** Settings ***
Shouldn't we add copyright also to this file?

2024-02-12 08:19 UTC, RobertPoienar commented on Bindings~/robot/tests/test_driver.robot
> +*** Settings ***
And for the rest of robot files?

2024-02-12 09:05 UTC, RobertPoienar approved these changes

2024-02-12 09:10 UTC, andreion1ca approved these changes

2024-02-12 09:14 UTC, merged