change methods names
alttester/AltTester-Unity-SDK pull request #971
Opened 2022-10-31 22:29 UTC by SandyEma9

2022-10-31 22:30 UTC, SandyEma9 commented
@robert-altom @RobertPoienar @gomboskriszta15

2022-11-01 07:12 UTC, RobertPoienar reviewed
Depending on what kind of release are we deciding to do (major or minor) this PR is correct or incorrect. Because it breaks backward compatibility if we decide to do a minor release then it would great if you mark the methods with small letters as deprecated and create new methods with correct syntax. If we decide to release a major version aka PRO then this is correct

2022-11-07 09:22 UTC, RobertPoienar requested changes
Mark the old methods as obsolete

2022-11-07 09:22 UTC, RobertPoienar commented on Assets/AltTester/AltDriver/Common/AltObject.cs
> +        public AltObject getParent()
Mark the methods Obsolete so users will know to use the other method. Here is how you can do it: https://stackoverflow.com/questions/1759352/how-to-mark-a-method-as-obsolete-or-deprecated

2022-11-07 09:22 UTC, RobertPoienar commented on Assets/AltTester/AltDriver/Common/AltObject.cs
> +        public AltVector2 getScreenPosition()
Also this one needs to be obsolete

2022-11-07 09:22 UTC, RobertPoienar commented on Assets/AltTester/AltDriver/Common/AltObject.cs
> +        public AltVector3 getWorldPosition()
and this one

2022-11-15 19:46 UTC, SandyEma9 commented
@RobertPoienar @robert-altom @ReichEdvin

2022-11-16 07:48 UTC, gomboskriszta15 approved these changes
👍

2022-11-16 07:51 UTC, merged