926 add  set static property command
alttester/AltTester-Unity-SDK pull request #975
Opened 2022-11-02 10:50 UTC by SandyEma9

2022-11-04 17:06 UTC, SandyEma9 commented
@RobertPoienar @robert-altom @gomboskriszta15 @ReichEdvin

2022-11-07 09:05 UTC, ReichEdvin commented on Bindings~/java/src/main/java/com/alttester/Commands/AltSetStaticProperty.java
> + * Get the value of a property from one of the component of the object.
It sets the value

2022-11-07 09:18 UTC, RobertPoienar requested changes
Added some comments, also you need to add this command to documentation

2022-11-07 09:18 UTC, RobertPoienar commented on Assets/AltTester/AltDriver/AltDriver.cs
> +        public void SetStaticProperty(string componentName, string propertyName, string assemblyName, object updatedProperty, int maxDepth = 2)
maxDepth is not needed

2022-11-07 09:18 UTC, RobertPoienar commented on Bindings~/java/src/main/java/com/alttester/AltDriver.java
> +     * @param parameters - String componentName* , String propertyName* , String
Don't have/need maxDepth

2022-11-08 09:05 UTC, ReichEdvin approved these changes
lgtm

2022-11-16 13:12 UTC, RobertPoienar approved these changes
LGTM

2022-11-16 13:12 UTC, merged